export const defaultPersona = {
  skin: {
    photoUrls: [],
    skinType: "",
    concerns: [],
    sensitivity: "",
    fitzpatrick: "",
    ingredientPreferences: [],
    brandPreferences: [],
    climate: "",
    notes: "",
    updatedAt: null,
  },

  hair: {
    photoUrls: [],
    hairType: "",
    density: "",
    scalpType: "",
    goals: [],
    lifestyleFactors: [],
    stylingHabits: "",
    notes: "",
    updatedAt: null,
  },

  body: {
    photoUrls: [],
    height: "",
    frame: "",
    proportions: "",
    shoulderWaistHip: "",
    bodyType: "",
    fitPreferences: "",
    activities: [],
    notes: "",
    updatedAt: null,
  },

  style: {
    styleArchetypes: [],
    colorPalette: [],
    boldness: "",
    occasions: [],
    footwear: [],
    accessories: [],
    notes: "",
    updatedAt: null,
  },

  taste: {
    giftingStyle: "",
    decorPreferences: [],
    scentPreferences: [],
    techPreferences: [],
    priceComfort: "",
    materialPreferences: [],
    sustainability: "",
    notes: "",
    updatedAt: null,
  },

  lifestyle: {
    workSetup: "",
    diet: "",
    fitness: "",
    travelFrequency: "",
    climate: "",
    routines: "",
    stress: "",
    sleep: "",
    notes: "",
    updatedAt: null,
  },
};
